name: 'Run textlint with reviewdog'
on: [pull_request]
jobs:
  textlint:
    runs-on: Ubuntu-latest
    container:
      image: node:current-alpine
      env:
        LEVEL: error
        FLAGS: articles/
    steps:
      - uses: actions/checkout@v1
      - name: setup-reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
      - name: install-textlint
        run: |
          cd "$GITHUB_WORKSPACE"
          if [ ! -f "$(npm bin)/textlint" ]; then
            npm install
          fi
      - name: run-reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $(npm bin)/textlint -f checkstyle "${FLAGS:-'.'}" \
            | reviewdog -f=checkstyle -name="textlint" -diff="Git diff HEAD^" -reporter=GitHub-pr-review -level="${LEVEL}"
